### ISSUE TITLE
AMO link is broken

### ISSUE THREAD

**Issue by fbender** [captainbrosset/domprofiler#25]
The link in the description to addons.mozilla.org leads to a 404. Did this move?

**Comment by captainbrosset** [comment]
Thanks for filing the issue. You're right.
I'm working on it. I will try to find some time this week to get this done (I actually need to re-submit a new version to AMO).

**Comment by fbender** [comment]
Thanks! 

I was going to suggest to you looking into [JPM](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm) though I just saw they're not accepting such addons yet – however this info might be outdated. Asked @erikvold [via Twitter](https://twitter.com/fbender_dev/status/534651708203606016) about that.

**Comment by captainbrosset** [comment]
Yeah I too saw that jpm addons weren't accepted yet.

**Comment by captainbrosset** [comment]
Removed the URL from the repo and from the readme, and filed #26 instead.

**Comment by fbender** [comment]
FYI: JPM will be compatible with Fx 37 (according to https://blog.mozilla.org/addons/2015/01/07/jetpack-in-2014/).

**Comment by captainbrosset** [comment]
Thanks for that!
